let x = ""

while(x === ""){
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    document.getElementById("haha").textContent = "haha"
    
}